### ISSUE TITLE
Opacity Slider Not Working

### ISSUE THREAD

**Issue by LukePrior** [mwasil/Leaflet.Rainviewer#3]
The Opacity slider doesn't seem to work correctly. It only adjusts the opacity of the current time and not the other ones in animation. You can see it in practice here: https://jsfiddle.net/hwmz670c/

**Comment by mwasil** [comment]
Seems to be working just fine :
![9GYUsRuqoH](https://user-images.githubusercontent.com/23232926/113708055-10499d80-96e1-11eb-8561-bbc9ab7ddbad.gif)

Could you please provide more details (browser, version, etc.)?

**Comment by LukePrior** [comment]
> Seems to be working just fine :
> ![9GYUsRuqoH](https://user-images.githubusercontent.com/23232926/113708055-10499d80-96e1-11eb-8561-bbc9ab7ddbad.gif)
> 
> Could you please provide more details (browser, version, etc.)?

Hi, 

The problem occurs once the user has started the animation using the Start/Stop button, if they then adjust the slider the current layer in animation is updated. Once the automatic animation goes to the next time period the opacity defaults.

I will get a gif and more information for you.

**Comment by LukePrior** [comment]
While I was creating the example I was wondering if there is anyway to just have the overlay show up in the normal leaflet layer selection menu. The animation speed and opacity could just be set in the JavaScript setup and it would improve simplicity.

![Screenshot_2021-04-06-22-16-18-96](https://user-images.githubusercontent.com/22492406/113709363-c040fa00-9725-11eb-909f-c91e20198a04.jpg)

Cheers

**Comment by mwasil** [comment]
It is possible, but requires a deep modifications of the plugin, or rather writing a new one.

**Comment by PedroVenancio** [comment]
> ![Screenshot_2021-04-06-22-16-18-96](https://user-images.githubusercontent.com/22492406/113709363-c040fa00-9725-11eb-909f-c91e20198a04.jpg)

Hi @LukePrior 
Sorry for the off-topic, but can you share the source of your "NOAA - Global Wind" layer?
Thanks and sorry again!

**Comment by LukePrior** [comment]
> Hi @LukePrior Sorry for the off-topic, but can you share the source of your "NOAA - Global Wind" layer? Thanks and sorry again!

I think I was using this: https://github.com/danwild/wind-js-leaflet or https://github.com/onaci/leaflet-velocity
