### ISSUE TITLE
Typo in Setup section of README.md

### ISSUE THREAD

**Issue by openwebcc** [mwasil/Leaflet.Rainviewer#4]
There's a typo in the example code of [https://github.com/mwasil/Leaflet.Rainviewer#setup](https://github.com/mwasil/Leaflet.Rainviewer#setup)

`L.control.rainviwer` should be `L.control.rainviewer`

**Comment by mwasil** [comment]
Fixed! Thanks!

**Comment by openwebcc** [comment]
Thank you too for providing the Plugin
